name: .NET CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore CyberSecurityChatBot.sln  # 🔧 Replace with the actual path to your .sln or .csproj

    - name: Build
      run: dotnet build CyberSecurityChatBot.sln --no-restore  # 🔧 Optional: also specify here

    - name: Test
      run: dotnet test CyberSecurityChatBot.sln --no-build --verbosity normal  # 🔧 Optional: also specify here

